# /Users/jesseatkinson/.config/tmuxinator/☭.yml

name: ☭
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Project hooks
# Runs on project start, always
# on_project_start: command
# Run on project start, the first time
# on_project_first_start: command
# Run on project start, after the first time
# on_project_restart: command
# Run on project exit ( detaching from tmux session )
# on_project_exit: command
# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# tmuxinator starts *not* using your login shell, but rather /bin/sh or /bin/bash.
# For reasons I do not understand we must tell tmuxinator to start tmux with
# $TERM set to `screen-256color`.  Then in ~/.tmux.conf we tell tmux to use the
# default-terminal of `tmux-256color`.  Terminal emulators + terminal
# multiplexers + terminfo = weird font stuff ¯\_(ツ)_/¯.
# See: https://github.com/tmuxinator/tmuxinator/issues/300
tmux_command: env TERM=screen-256color tmux -2

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t ☃︎

windows:
  - "📧":
      panes:
        - mail:
          - mutt
          - O # Syncs mail
  - "💬": weechat
  - "🛠 ": # Intentional extra space because... unicode.
      root: "~/.dotfiles"
  - "🐠":
      root: "~"
