# This is an implementation of the Riseup OpenPGP Best Practices & Dr Duh's
# YubiKey Guide.
#
# References
# - https://help.riseup.net/en/security/message-security/openpgp/best-practices
# - https://github.com/drduh/YubiKey-Guide/blob/master/README.md


# Default Key {{{1

# The default key to sign with.  If this option is not used, the default key is
# the first key found in the secret keyring.
default-key AAAAC3NzaC1lZDI1NTE5AAAAIPNX7+oToJga7egi3IU3v1znfHqKVqJv8RuZaiaaCuFZ

# Behavior {{{1

# Disable inclusion of the version string in ASCII armored output.
no-emit-version

# Disable comment string in clear text signatures and ASCII armored messages
no-comments

# Display long key IDs
keyid-format 0xlong

personal-cipher-preferences AES256 AES192 AES
personal-digest-preferences SHA512 SHA384 SHA256 SHA224
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed
cert-digest-algo SHA512
s2k-cipher-algo AES256
s2k-digest-algo SHA512
charset utf-8
fixed-list-mode
list-options show-uid-validity
verify-options show-uid-validity
with-fingerprint
use-agent
require-cross-certification

# Keyserver {{{1

auto-key-locate keyserver

# Default keyserver set in dirmngr.conf.  Which as of this
# writing defaults to keys.openpgp.org.

# When using --refresh-keys, if the key in question has a preferred keyserver
# URL, then disable use of that preferred keyserver to refresh the key from
keyserver-options no-honor-keyserver-url

# When searching for a key with --search-keys, include keys that are marked on
# the keyserver as revoked
keyserver-options include-revoked

# vim: set foldmethod=marker syntax=gpg:
