# Basics {{{

# Load .bashrc if it exists
test -f ~/.bashrc && source ~/.bashrc

# }}}
# Environment Variables {{{

export BREW_PREFIX=$(/usr/local/bin/brew --prefix)

# }}}
# Path {{{

export PATH=$PATH:$HOME/.asdf/installs/rust/stable/bin
export PATH=$PATH:$HOME/.asdf/shims
export PATH=$PATH:$BREW_PREFIX/bin:$BREW_PREFIX/sbin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:$HOME/.config/scripts

# }}}
# Files I need to source {{{

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

if [ -f $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash ]; then
  . $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash
fi

# }}}
# vim: set foldmethod=marker foldmarker={{{,}}} syntax=sh:
