#!/usr/bin/env osascript
# Returns the current playing song in Spotify for OSX
# Stolen from: https://github.com/dickeyxxx/tmux-spotify-info/blob/master/tmux-spotify-info
# TODO: Get this to cut at a certain amount and scroll

tell application "Spotify"
  if it is running then
    if player state is playing then
      set track_name to name of current track
      set artist_name to artist of current track

      if artist_name > 0
        # If the track has an artist set and is therefore most likely a song rather than an advert
        "#[fg=colour125]♬#[fg=colour232]  \"" & track_name & "\" by " & artist_name
      else
        # If the track doesn't have an artist set and is therefore most likely an advert rather than a song
        "#[fg=colour125]♬#[fg=colour232]  ~ " & track_name
      end if
    else
      "🔇 "
    end if
  else
		"🔇 "
  end if
end tell
